---
# log level (optional, defaults to "info")
# log_level: "debug"

# log path (optional, defaults to STDERR)
# log_path: 'p4-bench.log'

# path to output directory
out_dir: "out"

# array of hosts to benchmark
# (order determines output order)
hosts:
  - name: "pi0w-zero"
    host: "zero"
    text: "Raspberry Pi Zero W"
    set:  "arm"

  - name: "pi3b-pecan"
    host: "pecan"
    text: "Raspberry Pi 3 Model B"
    set:  "arm"

  - name: "pi3b+-peach"
    host: "peach"
    text: "Raspberry Pi 3 Model B+"
    set:  "arm"

  - name: "pi4b-cherry"
    host: "cherry"
    text: "Raspberry Pi 4 Model B"
    set:  "arm"

  - name: "linode"
    host: "pmdn.org"
    text: "Linode VM (1 Core)"
    set:  "x86"

  - name: "i78650u-flex"
    host: "flex"
    text: "Intel i7-8650U (Lenovo X1 Carbon, 6th Gen)"
    set:  "x86"

  - name: "tr1950x-v4"
    host: "v4.wg"
    text: "AMD Ryzen Threadripper 1950X"
    set:  "x86"

# list of algorithms to test (optional)
# algos:
#   - blake2b512
#   - blake2s256
#   - sha256
#   - sha512
#   - aes-128-cbc
#   - aes-192-cbc
#   - aes-256-cbc
